version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=localhost
      - DB_NAME=newdb
      - DB_USER=postgres
      - DB_PASS=prodaft123*
    depends_on:
      - db
      
  db:
    image: postgres
    environment:
      - POSTGRES_DB=newdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prodaft123*
    volumes:
      - Xvolume:/var/lib/postgresql/data
      
volumes:
  Xvolume:
